
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: lab_postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: labdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - covid-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labuser -d labdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: lab_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: labuser
      DB_PASSWORD: labpass
      DB_NAME: labdb
      FLASK_PORT: 5000
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - covid-network
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: lab_frontend
    ports:
      - "5173:5173"
    networks:
      - covid-network
    environment:
      - VITE_API_BASE_URL=http://localhost:5001/api

volumes:
  db_data:

networks:
  covid-network:
    driver: bridge
