[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["cd Backend && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd Backend && gunicorn --bind 0.0.0.0:$PORT run:app"
